;;;=========================================================================;;;
;;; Copyright 2022 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Annalog.                                           ;;;
;;;                                                                         ;;;
;;; Annalog is free software: you can redistribute it and/or modify it      ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Annalog is distributed in the hope that it will be useful, but WITHOUT  ;;;
;;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   ;;;
;;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ;;;
;;; for more details.                                                       ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Annalog.  If not, see <http://www.gnu.org/licenses/>.              ;;;
;;;=========================================================================;;;

;;; BG tile IDs for animating the mine boss emerging from the wall.
kTileIdBgAnimWyrmFirst = $40
;;; BG tile IDs for drawing the conveyor for the mine boss.
kTileIdBgTerrainConveyorFirst = $b8

;;; OBJ tile IDs for drawing the mine boss.
kTileIdObjBossMineEyeFirst = $d8

;;; The OBJ palette number to use for drawing the mine boss's eye.
kPaletteObjBossMineEye = 1

;;;=========================================================================;;;
