name = "Monochrome Caves"
artist = "Adam Saltsman"
license = "Public Domain"
year = 2018
url = "https://adamatomic.itch.io/mc-caves"
comments = """
Some of these tiles have been modified from the original.
"""
