[[sources]]
name = "Pixel Portraits 32x32"
artist = "Exuin"
license = "CC0"
year = 2021
url = "https://opengameart.org/content/pixel-portraits-32x32"
comments = """
These portraits have been modified from their originals.
"""

[[sources]]
name = "32x32 Fantasy portrait set"
artist = "CobraLad"
license = "CC-BY 3.0"
year = 2015
url = "https://opengameart.org/content/32x32-fantasy-portrait-set"
comments = """
These portraits have been modified from their originals.
"""
