name = "Battle Sounds >> Ugh.wav"
artist = "Luke Sharples"
license = "CC-BY 4.0"
year = 2013
url = "https://freesound.org/people/LukeSharples/sounds/209181/"
comments = """
This file has been modified from the original.
"""
