;;;=========================================================================;;;
;;; Copyright 2022 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Annalog.                                           ;;;
;;;                                                                         ;;;
;;; Annalog is free software: you can redistribute it and/or modify it      ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Annalog is distributed in the hope that it will be useful, but WITHOUT  ;;;
;;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   ;;;
;;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ;;;
;;; for more details.                                                       ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Annalog.  If not, see <http://www.gnu.org/licenses/>.              ;;;
;;;=========================================================================;;;

;;; State bytes for adult/child/mermaid NPCs:
;;;   * State1: The first tile ID for the actor.
;;;   * State2: Unused.

;;; The first tile IDs for various children.
kTileIdChildPonytailFirst   = $84

;;; The first tile IDs for various adults.
kTileIdAdultWomanFirst      = $88

;;; The first tile IDs for various mermaids.
kTileIdMermaidAdultFirst    = $8e
kTileIdMermaidFloristFirst  = $94
kTileIdMermaidYouthFirst    = $9a
kTileIdMermaidGuardFFirst   = $a0
kTileIdMermaidPonytailFirst = $a6
kTileIdMermaidGuardMFirst   = $ac
kTileIdMermaidFarmerFirst   = $be
kTileIdMermaidQueenFirst    = $c4

;;;=========================================================================;;;
