;;;=========================================================================;;;
;;; Copyright 2022 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Annalog.                                           ;;;
;;;                                                                         ;;;
;;; Annalog is free software: you can redistribute it and/or modify it      ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Annalog is distributed in the hope that it will be useful, but WITHOUT  ;;;
;;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   ;;;
;;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ;;;
;;; for more details.                                                       ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Annalog.  If not, see <http://www.gnu.org/licenses/>.              ;;;
;;;=========================================================================;;;

.CHARMAP $20, $00  ; ' '
.CHARMAP $21, $01  ; '!'
.CHARMAP $3f, $02  ; '?'
.CHARMAP $2e, $03  ; '.'
.CHARMAP $3a, $04  ; ':'
.CHARMAP $2c, $05  ; ','
.CHARMAP $27, $06  ; "'"
.CHARMAP $2b, $07  ; '+'
.CHARMAP $2d, $08  ; '-'
.CHARMAP $3c, $0b  ; '<'
.CHARMAP $3d, $09  ; '='
.CHARMAP $3e, $0d  ; '>'

.CHARMAP $30, $10  ; '0'
.CHARMAP $31, $11  ; '1'
.CHARMAP $32, $12  ; '2'
.CHARMAP $33, $13  ; '3'
.CHARMAP $34, $14  ; '4'
.CHARMAP $35, $15  ; '5'
.CHARMAP $36, $16  ; '6'
.CHARMAP $37, $17  ; '7'
.CHARMAP $38, $18  ; '8'
.CHARMAP $39, $19  ; '9'

.CHARMAP $41, $20  ; 'A'
.CHARMAP $42, $21  ; 'B'
.CHARMAP $43, $22  ; 'C'
.CHARMAP $44, $23  ; 'D'
.CHARMAP $45, $24  ; 'E'
.CHARMAP $46, $25  ; 'F'
.CHARMAP $47, $26  ; 'G'
.CHARMAP $48, $27  ; 'H'
.CHARMAP $49, $28  ; 'I'
.CHARMAP $4a, $29  ; 'J'
.CHARMAP $4b, $2a  ; 'K'
.CHARMAP $4c, $2b  ; 'L'
.CHARMAP $4d, $2c  ; 'M'
.CHARMAP $4e, $2d  ; 'N'
.CHARMAP $4f, $2e  ; 'O'
.CHARMAP $50, $2f  ; 'P'
.CHARMAP $51, $30  ; 'Q'
.CHARMAP $52, $31  ; 'R'
.CHARMAP $53, $32  ; 'S'
.CHARMAP $54, $33  ; 'T'
.CHARMAP $55, $34  ; 'U'
.CHARMAP $56, $35  ; 'V'
.CHARMAP $57, $36  ; 'W'
.CHARMAP $58, $37  ; 'X'
.CHARMAP $59, $38  ; 'Y'
.CHARMAP $5a, $39  ; 'Z'

.CHARMAP $61, $40  ; 'a'
.CHARMAP $62, $41  ; 'b'
.CHARMAP $63, $42  ; 'c'
.CHARMAP $64, $43  ; 'd'
.CHARMAP $65, $44  ; 'e'
.CHARMAP $66, $45  ; 'f'
.CHARMAP $67, $46  ; 'g'
.CHARMAP $68, $47  ; 'h'
.CHARMAP $69, $48  ; 'i'
.CHARMAP $6a, $49  ; 'j'
.CHARMAP $6b, $4a  ; 'k'
.CHARMAP $6c, $4b  ; 'l'
.CHARMAP $6d, $4c  ; 'm'
.CHARMAP $6e, $4d  ; 'n'
.CHARMAP $6f, $4e  ; 'o'
.CHARMAP $70, $4f  ; 'p'
.CHARMAP $71, $50  ; 'q'
.CHARMAP $72, $51  ; 'r'
.CHARMAP $73, $52  ; 's'
.CHARMAP $74, $53  ; 't'
.CHARMAP $75, $54  ; 'u'
.CHARMAP $76, $55  ; 'v'
.CHARMAP $77, $56  ; 'w'
.CHARMAP $78, $57  ; 'x'
.CHARMAP $79, $58  ; 'y'
.CHARMAP $7a, $59  ; 'z'

;;;=========================================================================;;;
