;;;=========================================================================;;;
;;; Copyright 2022 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Annalog.                                           ;;;
;;;                                                                         ;;;
;;; Annalog is free software: you can redistribute it and/or modify it      ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Annalog is distributed in the hope that it will be useful, but WITHOUT  ;;;
;;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   ;;;
;;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ;;;
;;; for more details.                                                       ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Annalog.  If not, see <http://www.gnu.org/licenses/>.              ;;;
;;;=========================================================================;;;

;;; The CHR bank numbers containing various dialog portrait tiles.
kChrBankPortraitAlexRest    = $01
kChrBankPortraitAlexTalk    = $02
kChrBankPortraitBrunoRest   = $0b
kChrBankPortraitBrunoTalk   = $0c
kChrBankPortraitCorraRest   = $09
kChrBankPortraitCorraTalk   = $0a
kChrBankPortraitEireneRest  = $03
kChrBankPortraitEireneTalk  = $04
kChrBankPortraitElderRest   = $0f
kChrBankPortraitElderTalk   = $10
kChrBankPortraitFarmerRest  = $0f
kChrBankPortraitFarmerTalk  = $10
kChrBankPortraitFloristRest = $05
kChrBankPortraitFloristTalk = $06
kChrBankPortraitGrontaRest  = $05
kChrBankPortraitGrontaTalk  = $06
kChrBankPortraitJeromeRest  = $11
kChrBankPortraitJeromeTalk  = $12
kChrBankPortraitManRest     = $0d
kChrBankPortraitManTalk     = $0e
kChrBankPortraitMarieRest   = $09
kChrBankPortraitMarieTalk   = $0a
kChrBankPortraitMermaidRest = $07
kChrBankPortraitMermaidTalk = $08
kChrBankPortraitNoraRest    = $0b
kChrBankPortraitNoraTalk    = $0c
kChrBankPortraitOrcRest     = $07
kChrBankPortraitOrcTalk     = $08
kChrBankPortraitPaper       = $01
kChrBankPortraitPlaque      = $02
kChrBankPortraitScreen      = $03
kChrBankPortraitSign        = $04
kChrBankPortraitWomanRest   = $0d
kChrBankPortraitWomanTalk   = $0e

;;;=========================================================================;;;

;;; BG tile IDs for various dialog portraits.
kTileIdBgPortraitAlexFirst    = $c0
kTileIdBgPortraitBrunoFirst   = $d0
kTileIdBgPortraitCorraFirst   = $c0
kTileIdBgPortraitEireneFirst  = $c0
kTileIdBgPortraitElderFirst   = $c0
kTileIdBgPortraitFarmerFirst  = $d0
kTileIdBgPortraitFloristFirst = $d0
kTileIdBgPortraitGrontaFirst  = $c0
kTileIdBgPortraitJeromeFirst  = $c0
kTileIdBgPortraitManFirst     = $d0
kTileIdBgPortraitMarieFirst   = $d0
kTileIdBgPortraitMermaidFirst = $d0
kTileIdBgPortraitNoraFirst    = $c0
kTileIdBgPortraitOrcFirst     = $c0
kTileIdBgPortraitPaperFirst   = $d0
kTileIdBgPortraitPlaqueFirst  = $d0
kTileIdBgPortraitScreenFirst  = $d0
kTileIdBgPortraitSignFirst    = $d0
kTileIdBgPortraitWomanFirst   = $c0

;;;=========================================================================;;;
