;;;=========================================================================;;;
;;; Copyright 2022 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Annalog.                                           ;;;
;;;                                                                         ;;;
;;; Annalog is free software: you can redistribute it and/or modify it      ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Annalog is distributed in the hope that it will be useful, but WITHOUT  ;;;
;;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   ;;;
;;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ;;;
;;; for more details.                                                       ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Annalog.  If not, see <http://www.gnu.org/licenses/>.              ;;;
;;;=========================================================================;;;

;;; The CHR bank numbers containing various dialog portrait tiles.
kChrBankPortraitAlexRest    = $0b
kChrBankPortraitAlexTalk    = $0c
kChrBankPortraitBrunoRest   = $13
kChrBankPortraitBrunoTalk   = $14
kChrBankPortraitCorraRest   = $0d
kChrBankPortraitCorraTalk   = $0e
kChrBankPortraitEireneRest  = $1b
kChrBankPortraitEireneTalk  = $1c
kChrBankPortraitFloristRest = $0f
kChrBankPortraitFloristTalk = $10
kChrBankPortraitGrontaRest  = $16
kChrBankPortraitGrontaTalk  = $17
kChrBankPortraitManRest     = $07
kChrBankPortraitManTalk     = $08
kChrBankPortraitMarieRest   = $11
kChrBankPortraitMarieTalk   = $12
kChrBankPortraitMermaidRest = $05
kChrBankPortraitMermaidTalk = $06
kChrBankPortraitNoraRest    = $09
kChrBankPortraitNoraTalk    = $0a
kChrBankPortraitOrcRest     = $18
kChrBankPortraitOrcTalk     = $19
kChrBankPortraitPaper       = $0e
kChrBankPortraitPlaque      = $15
kChrBankPortraitScreen      = $1a
kChrBankPortraitSign        = $03
kChrBankPortraitWomanRest   = $01
kChrBankPortraitWomanTalk   = $02

;;;=========================================================================;;;

;;; BG tile IDs for various dialog portraits.
kTileIdBgPortraitAlexFirst    = $70
kTileIdBgPortraitBrunoFirst   = $70
kTileIdBgPortraitCorraFirst   = $70
kTileIdBgPortraitEireneFirst  = $70
kTileIdBgPortraitFloristFirst = $70
kTileIdBgPortraitGrontaFirst  = $70
kTileIdBgPortraitManFirst     = $70
kTileIdBgPortraitMarieFirst   = $70
kTileIdBgPortraitMermaidFirst = $70
kTileIdBgPortraitNoraFirst    = $70
kTileIdBgPortraitOrcFirst     = $70
kTileIdBgPortraitPaperFirst   = $60
kTileIdBgPortraitPlaqueFirst  = $70
kTileIdBgPortraitScreenFirst  = $70
kTileIdBgPortraitSignFirst    = $70
kTileIdBgPortraitWomanFirst   = $70

;;;=========================================================================;;;
