;;;=========================================================================;;;
;;; Copyright 2022 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Annalog.                                           ;;;
;;;                                                                         ;;;
;;; Annalog is free software: you can redistribute it and/or modify it      ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Annalog is distributed in the hope that it will be useful, but WITHOUT  ;;;
;;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   ;;;
;;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ;;;
;;; for more details.                                                       ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Annalog.  If not, see <http://www.gnu.org/licenses/>.              ;;;
;;;=========================================================================;;;

;;; Samples that can be played on the DMC as sound effects.
.ENUM eSample
    BossRoar0   ; a boss roar (deepest)
    BossRoar1   ; a boss roar
    BossRoar2   ; a boss roar
    BossRoar3   ; a boss roar
    BossRoar4   ; a boss roar
    BossRoar5   ; a boss roar
    BossRoar6   ; a boss roar
    BossRoar7   ; a boss roar
    BossRoar8   ; a boss roar (highest)
    BossHurtD   ; a boss gets hurt (deepest)
    BossHurtE   ; a boss gets hurt (medium)
    BossHurtF   ; a boss gets hurt (highest)
    Harm        ; when Anna gets hurt
    JumpAnna    ; when Anna jumps
    JumpGronta  ; when Gronta jumps
    NUM_VALUES
.ENDENUM

;;;=========================================================================;;;
