;;;=========================================================================;;;
;;; Copyright 2022 Matthew D. Steele <mdsteele@alum.mit.edu>                ;;;
;;;                                                                         ;;;
;;; This file is part of Annalog.                                           ;;;
;;;                                                                         ;;;
;;; Annalog is free software: you can redistribute it and/or modify it      ;;;
;;; under the terms of the GNU General Public License as published by the   ;;;
;;; Free Software Foundation, either version 3 of the License, or (at your  ;;;
;;; option) any later version.                                              ;;;
;;;                                                                         ;;;
;;; Annalog is distributed in the hope that it will be useful, but WITHOUT  ;;;
;;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   ;;;
;;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ;;;
;;; for more details.                                                       ;;;
;;;                                                                         ;;;
;;; You should have received a copy of the GNU General Public License along ;;;
;;; with Annalog.  If not, see <http://www.gnu.org/licenses/>.              ;;;
;;;=========================================================================;;;

;;; Various OBJ tile IDs used for drawing upgrades.
kTileIdObjUpgradeBottomFirst   = $80
kTileIdObjUpgradeMaxInstFirst  = $82
kTileIdObjUpgradeBRemoteFirst  = $84
kTileIdObjUpgradeOpIfFirst     = $86
kTileIdObjUpgradeOpTilFirst    = $88
kTileIdObjUpgradeOpCopyFirst   = $8a
kTileIdObjUpgradeOpAddSubFirst = $8c
kTileIdObjUpgradeOpMulFirst    = $8e
kTileIdObjUpgradeOpBeepFirst   = $90
kTileIdObjUpgradeOpGotoFirst   = $92
kTileIdObjUpgradeOpSkipFirst   = $94
kTileIdObjUpgradeOpWaitFirst   = $96
kTileIdObjUpgradeOpSyncFirst   = $98

;;;=========================================================================;;;
